"""add email to user

Revision ID: 600ab4ff763d
Revises: 7a403ac85b72
Create Date: 2020-01-15 17:42:38.863800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600ab4ff763d'
down_revision = '7a403ac85b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
